server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  cloud:
    gateway:
      routes:
        - id: chat-service
          uri: http://localhost:8081/
          predicates:
            - Path=/chat-internal/**
        - id: post-service
          uri: http://localhost:8082/
          predicates:
            - Path=/post-internal/**
        - id: user-service
          uri: http://localhost:8083/
          predicates:
            - Path=/user-internal/**
